# Generated by Django 5.0.6 on 2024-06-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0004_question_choice1_question_choice2_question_choice3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='true_false',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
